### PR TITLE
fixed problem with lexer patterns

### PR DESCRIPTION
**Pull request by VarS311**
Fix for issue #101

Reworked the Lexer patterns so identifiers are not confused with it

### CODE REVIEW

**Comment by VarS311** [comment]
Already ran another analysis with the code that caused this issue and it's correctly fixed

**Comment by JimmyRojas** [comment]
Please add a new test scenario to validate
ChartSettingBars.XAxis = m.APropValue

and adapt the unit-tests, do not delete them

**Comment by mounirRM** [comment]
Hi all, 

i'm trying to test the current version of the project, i always fall on the previous version of code (the code is not merged), Please, can anyone give me a solution for this?
Thank you

**Comment by ziur** [comment]
@mounirRM, today this pull request will be merged, as @JimmyRojas commented, it is still pending the related unit test.

**Pull request merged**
