### PR TITLE
Resolve SOQL Parsing Errors and 4 Custom Rules

### PR DESCRIPTION
**Pull request by rahulAppirio**
Resolve Most of the SOQL Parsing issue.

### CODE REVIEW

**Comment by rahulAppirio** [comment]
Resolve SOQL Parsing error
Write 4 custom rules

**Comment by CaesarSopranus** [comment]
Hi, i am very new on that, i installed this plugin but i have some parse issue. I can see that this branch modifications can solve the problem but nobody take care of the request. Is it possible to merge this modifications and have a new version of the plugin? Otherwise is possible for me to have this modification and have a new version of the plugin? Thank you very much

**Comment by rahulAppirio** [comment]
Hi CaesarSopranus,

I have merged this modification. You can try with this and let us know if any issue.

**Comment by CaesarSopranus** [comment]
Hello Rahul,
First of all thanks for your actions and reply very quick.
Sorry but i need to ask you, it is a long time i am not a developer anymore
and i don't know how to build myself the plugin.
The link on the plugin .jar download is still at version 1.0.0
Is there a way that i can have a built plugin?

Thanks in advance for your support

Best regards

Cesare

**Comment by CaesarSopranus** [comment]
Hello, forget my last comment.
I built the plugin with the merged code you provide. Is working but i have some warnings during the SoraQube analysis:

Apr 26, 2018 11:38:12 AM org.fundacionjala.enforce.sonarqube.apex.checks.HardcodingIdsCheckInVariables@63dfada0 visitNode
WARNING: java.lang.NullPointerException
Apr 26, 2018 11:38:12 AM org.fundacionjala.enforce.sonarqube.apex.checks.AsyncMethodsCheck@6f231ced visitNode
WARNING: java.lang.NullPointerException

Could you help me on that?
Btw the analysis succeed and i have the data in the sonar dashboard

Thanks a lot

Cesare

**Pull request merged**
