### PR TITLE
Update documentation in README.md

### PR DESCRIPTION
**Pull request by loqo71la**

### CODE REVIEW

**Comment by loqo71la** [comment]
@ziur @marcocdlv @JimmyRojas please review this documentation.

**Comment by JimmyRojas** [comment]
looks good to me.. :)

**Comment by loqo71la** [comment]
@marcocdlv Yes, I used the markdown format of gitlab.

**Comment by loqo71la** [comment]
@JimmyRojas, @marcocdlv, @ziur I corrected the observations they requested.

**Comment by JimmyRojas** [comment]
to merge it

**Pull request merged**
